export const dummyMatch = {
    "match_id": 7065049753,
    "barracks_status_dire": 63,
    "barracks_status_radiant": 3,
    "chat": null,
    "cluster": 185,
    "cosmetics": null,
    "dire_score": 37,
    "dire_team_id": null,
    "draft_timings": null,
    "duration": 1470,
    "engine": 1,
    "first_blood_time": 19,
    "game_mode": 23,
    "human_players": 10,
    "leagueid": 0,
    "lobby_type": 0,
    "match_seq_num": 5932625701,
    "negative_votes": 0,
    "objectives": null,
    "positive_votes": 0,
    "radiant_gold_adv": null,
    "radiant_score": 30,
    "radiant_team_id": null,
    "radiant_win": false,
    "radiant_xp_adv": null,
    "skill": null,
    "start_time": 1679081451,
    "teamfights": null,
    "tower_status_dire": 1958,
    "tower_status_radiant": 4,
    "version": null,
    "replay_salt": 1209713151,
    "series_id": 0,
    "series_type": 0,
    "players": [
        {
            "match_id": 7065049753,
            "player_slot": 0,
            "ability_targets": null,
            "ability_upgrades_arr": [
                5233,
                5235,
                5233,
                5234,
                5233,
                7304,
                5233,
                5235,
                5234,
                5235,
                7304,
                6366,
                5234,
                5234,
                1018,
                5235,
                7304,
                6528,
                6049
            ],
            "ability_uses": null,
            "account_id": 164029252,
            "actions": null,
            "additional_units": null,
            "assists": 14,
            "backpack_0": 0,
            "backpack_1": 0,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 10,
            "denies": 3,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 1496,
            "gold_per_min": 613,
            "gold_reasons": null,
            "gold_spent": 11875,
            "gold_t": null,
            "hero_damage": 13758,
            "hero_healing": 5336,
            "hero_hits": null,
            "hero_id": 50,
            "item_0": 267,
            "item_1": 231,
            "item_2": 240,
            "item_3": 38,
            "item_4": 42,
            "item_5": 188,
            "item_neutral": 309,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 2,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 48,
            "leaver_status": 0,
            "level": 25,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 11326,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 0,
            "party_size": 1,
            "performance_others": null,
            "permanent_buffs": [
                {
                    "permanent_buff": 12,
                    "stack_count": 0,
                    "grant_time": 957
                }
            ],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 169,
            "towers_killed": null,
            "xp_per_min": 1633,
            "xp_reasons": null,
            "xp_t": null,
            "personaname": "СахарныйБолтЪ",
            "name": null,
            "last_login": null,
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": true,
            "win": 0,
            "lose": 1,
            "total_gold": 15018,
            "total_xp": 40008,
            "kills_per_min": 0.08163265306122448,
            "kda": 1,
            "abandons": 0,
            "rank_tier": 32,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 613,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1633,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.08163265306122448,
                    "pct": 0.35
                },
                "last_hits_per_min": {
                    "raw": 1.959183673469388,
                    "pct": 0.95
                },
                "hero_damage_per_min": {
                    "raw": 561.5510204081634,
                    "pct": 1
                },
                "hero_healing_per_min": {
                    "raw": 217.79591836734693,
                    "pct": 0.35
                },
                "tower_damage": {
                    "raw": 169,
                    "pct": 0.5
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0.1
                },
                "lhten": {}
            }
        },
        {
            "match_id": 7065049753,
            "player_slot": 1,
            "ability_targets": null,
            "ability_upgrades_arr": [
                343,
                5019,
                5632,
                343,
                5019,
                5022,
                343,
                5019,
                343,
                5019,
                5632,
                5022,
                5632,
                5632,
                6209,
                1087,
                5022,
                6202,
                6280
            ],
            "ability_uses": null,
            "account_id": null,
            "actions": null,
            "additional_units": null,
            "assists": 2,
            "backpack_0": 0,
            "backpack_1": 0,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 4,
            "denies": 5,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 468,
            "gold_per_min": 989,
            "gold_reasons": null,
            "gold_spent": 25025,
            "gold_t": null,
            "hero_damage": 15139,
            "hero_healing": 195,
            "hero_hits": null,
            "hero_id": 6,
            "item_0": 225,
            "item_1": 139,
            "item_2": 263,
            "item_3": 63,
            "item_4": 30,
            "item_5": 116,
            "item_neutral": 571,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 5,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 134,
            "leaver_status": 0,
            "level": 26,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 22218,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 1,
            "party_size": 1,
            "performance_others": null,
            "permanent_buffs": [
                {
                    "permanent_buff": 12,
                    "stack_count": 0,
                    "grant_time": 924
                }
            ],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 1282,
            "towers_killed": null,
            "xp_per_min": 1641,
            "xp_reasons": null,
            "xp_t": null,
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": true,
            "win": 0,
            "lose": 1,
            "total_gold": 24230,
            "total_xp": 40204,
            "kills_per_min": 0.20408163265306123,
            "kda": 1,
            "abandons": 0,
            "rank_tier": null,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 989,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1641,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.20408163265306123,
                    "pct": 0.4358974358974359
                },
                "last_hits_per_min": {
                    "raw": 5.469387755102041,
                    "pct": 0.05128205128205128
                },
                "hero_damage_per_min": {
                    "raw": 617.9183673469388,
                    "pct": 0.358974358974359
                },
                "hero_healing_per_min": {
                    "raw": 7.959183673469388,
                    "pct": 1
                },
                "tower_damage": {
                    "raw": 1282,
                    "pct": 0.3076923076923077
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0.9487179487179487
                },
                "lhten": {}
            }
        },
        {
            "match_id": 7065049753,
            "player_slot": 2,
            "ability_targets": null,
            "ability_upgrades_arr": [
                5186,
                5188,
                5186,
                5188,
                5186,
                5189,
                5186,
                5188,
                5188,
                5959,
                5187,
                5189,
                5187,
                5187,
                5187,
                6448,
                5189,
                6220,
                6403
            ],
            "ability_uses": null,
            "account_id": 367396390,
            "actions": null,
            "additional_units": null,
            "assists": 6,
            "backpack_0": 0,
            "backpack_1": 0,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 7,
            "denies": 1,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 1924,
            "gold_per_min": 1022,
            "gold_reasons": null,
            "gold_spent": 21110,
            "gold_t": null,
            "hero_damage": 34460,
            "hero_healing": 1111,
            "hero_hits": null,
            "hero_id": 45,
            "item_0": 273,
            "item_1": 692,
            "item_2": 610,
            "item_3": 108,
            "item_4": 180,
            "item_5": 36,
            "item_neutral": 589,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 14,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 113,
            "leaver_status": 0,
            "level": 26,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 22099,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 2,
            "party_size": 3,
            "performance_others": null,
            "permanent_buffs": [],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 1337,
            "towers_killed": null,
            "xp_per_min": 1656,
            "xp_reasons": null,
            "xp_t": null,
            "personaname": "Шара Буллет",
            "name": null,
            "last_login": "2023-03-18T14:54:14.368Z",
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": true,
            "win": 0,
            "lose": 1,
            "total_gold": 25039,
            "total_xp": 40572,
            "kills_per_min": 0.5714285714285714,
            "kda": 2,
            "abandons": 0,
            "rank_tier": 52,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 1022,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1656,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.5714285714285715,
                    "pct": 1
                },
                "last_hits_per_min": {
                    "raw": 4.612244897959183,
                    "pct": 0.7
                },
                "hero_damage_per_min": {
                    "raw": 1406.5306122448978,
                    "pct": 1
                },
                "hero_healing_per_min": {
                    "raw": 45.3469387755102,
                    "pct": 0.7
                },
                "tower_damage": {
                    "raw": 1337,
                    "pct": 0.2
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0.7
                },
                "lhten": {}
            }
        },
        {
            "match_id": 7065049753,
            "player_slot": 3,
            "ability_targets": null,
            "ability_upgrades_arr": [
                5048,
                5050,
                5051,
                5051,
                5051,
                5048,
                5051,
                5048,
                5048,
                5049,
                5050,
                5049,
                5050,
                5050,
                6397,
                702,
                5049,
                6692
            ],
            "ability_uses": null,
            "account_id": null,
            "actions": null,
            "additional_units": null,
            "assists": 14,
            "backpack_0": 0,
            "backpack_1": 0,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 11,
            "denies": 0,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 2995,
            "gold_per_min": 824,
            "gold_reasons": null,
            "gold_spent": 16315,
            "gold_t": null,
            "hero_damage": 23218,
            "hero_healing": 0,
            "hero_hits": null,
            "hero_id": 9,
            "item_0": 180,
            "item_1": 40,
            "item_2": 100,
            "item_3": 176,
            "item_4": 108,
            "item_5": 36,
            "item_neutral": 357,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 6,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 80,
            "leaver_status": 0,
            "level": 24,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 17900,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 2,
            "party_size": 3,
            "performance_others": null,
            "permanent_buffs": [
                {
                    "permanent_buff": 6,
                    "stack_count": 1,
                    "grant_time": 1416
                },
                {
                    "permanent_buff": 12,
                    "stack_count": 0,
                    "grant_time": 1103
                }
            ],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 472,
            "towers_killed": null,
            "xp_per_min": 1382,
            "xp_reasons": null,
            "xp_t": null,
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": true,
            "win": 0,
            "lose": 1,
            "total_gold": 20188,
            "total_xp": 33859,
            "kills_per_min": 0.24489795918367346,
            "kda": 1,
            "abandons": 0,
            "rank_tier": null,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 824,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1382,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.2448979591836735,
                    "pct": 0.8181818181818182
                },
                "last_hits_per_min": {
                    "raw": 3.2653061224489797,
                    "pct": 0.9272727272727272
                },
                "hero_damage_per_min": {
                    "raw": 947.6734693877551,
                    "pct": 1
                },
                "hero_healing_per_min": {
                    "raw": 0,
                    "pct": 0.4909090909090909
                },
                "tower_damage": {
                    "raw": 472,
                    "pct": 0.45454545454545453
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0
                },
                "lhten": {}
            }
        },
        {
            "match_id": 7065049753,
            "player_slot": 4,
            "ability_targets": null,
            "ability_upgrades_arr": [
                5024,
                5023,
                5025,
                5024,
                5024,
                5025,
                5026,
                5024,
                5025,
                5025,
                706,
                5023,
                5026,
                5023,
                918,
                5023,
                5026,
                6425,
                6035
            ],
            "ability_uses": null,
            "account_id": 81574831,
            "actions": null,
            "additional_units": null,
            "assists": 10,
            "backpack_0": 0,
            "backpack_1": 0,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 5,
            "denies": 1,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 1290,
            "gold_per_min": 701,
            "gold_reasons": null,
            "gold_spent": 14965,
            "gold_t": null,
            "hero_damage": 19504,
            "hero_healing": 0,
            "hero_hits": null,
            "hero_id": 7,
            "item_0": 0,
            "item_1": 119,
            "item_2": 50,
            "item_3": 1,
            "item_4": 108,
            "item_5": 11,
            "item_neutral": 376,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 2,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 84,
            "leaver_status": 0,
            "level": 25,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 14390,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 2,
            "party_size": 3,
            "performance_others": null,
            "permanent_buffs": [
                {
                    "permanent_buff": 6,
                    "stack_count": 1,
                    "grant_time": 844
                }
            ],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 287,
            "towers_killed": null,
            "xp_per_min": 1577,
            "xp_reasons": null,
            "xp_t": null,
            "personaname": "Ашик Галлардо",
            "name": null,
            "last_login": null,
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": true,
            "win": 0,
            "lose": 1,
            "total_gold": 17174,
            "total_xp": 38636,
            "kills_per_min": 0.08163265306122448,
            "kda": 2,
            "abandons": 0,
            "rank_tier": 41,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 701,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1577,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.08163265306122448,
                    "pct": 0.3333333333333333
                },
                "last_hits_per_min": {
                    "raw": 3.4285714285714284,
                    "pct": 0.6666666666666666
                },
                "hero_damage_per_min": {
                    "raw": 796.0816326530612,
                    "pct": 0.8666666666666667
                },
                "hero_healing_per_min": {
                    "raw": 0,
                    "pct": 0.8666666666666667
                },
                "tower_damage": {
                    "raw": 287,
                    "pct": 0.3333333333333333
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0
                },
                "lhten": {}
            }
        },
        {
            "match_id": 7065049753,
            "player_slot": 128,
            "ability_targets": null,
            "ability_upgrades_arr": [
                5581,
                5582,
                5581,
                5582,
                5581,
                5584,
                5583,
                5581,
                5583,
                5583,
                5584,
                5925,
                5582,
                5582,
                6884,
                5583,
                5584,
                6885,
                6921,
                6034
            ],
            "ability_uses": null,
            "account_id": null,
            "actions": null,
            "additional_units": null,
            "assists": 16,
            "backpack_0": 0,
            "backpack_1": 0,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 11,
            "denies": 4,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 5134,
            "gold_per_min": 1158,
            "gold_reasons": null,
            "gold_spent": 24680,
            "gold_t": null,
            "hero_damage": 29930,
            "hero_healing": 0,
            "hero_hits": null,
            "hero_id": 101,
            "item_0": 176,
            "item_1": 604,
            "item_2": 206,
            "item_3": 0,
            "item_4": 235,
            "item_5": 48,
            "item_neutral": 680,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 10,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 43,
            "leaver_status": 0,
            "level": 27,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 27109,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 3,
            "party_size": 2,
            "performance_others": null,
            "permanent_buffs": [
                {
                    "permanent_buff": 6,
                    "stack_count": 1,
                    "grant_time": 1499
                }
            ],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 1275,
            "towers_killed": null,
            "xp_per_min": 1484,
            "xp_reasons": null,
            "xp_t": null,
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": false,
            "win": 1,
            "lose": 0,
            "total_gold": 28371,
            "total_xp": 36358,
            "kills_per_min": 0.40816326530612246,
            "kda": 2,
            "abandons": 0,
            "rank_tier": null,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 1158,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1484,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.40816326530612246,
                    "pct": 1
                },
                "last_hits_per_min": {
                    "raw": 1.7551020408163265,
                    "pct": 0.8787878787878788
                },
                "hero_damage_per_min": {
                    "raw": 1221.6326530612246,
                    "pct": 1
                },
                "hero_healing_per_min": {
                    "raw": 0,
                    "pct": 0.8787878787878788
                },
                "tower_damage": {
                    "raw": 1275,
                    "pct": 1
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0.5757575757575758
                },
                "lhten": {}
            }
        },
        {
            "match_id": 7065049753,
            "player_slot": 129,
            "ability_targets": null,
            "ability_upgrades_arr": [
                5182,
                5184,
                5691,
                5691,
                5184,
                5185,
                5184,
                5184,
                5182,
                867,
                5182,
                5185,
                5182,
                5691,
                7388,
                5691,
                5185,
                6128,
                7001,
                856,
                868
            ],
            "ability_uses": null,
            "account_id": null,
            "actions": null,
            "additional_units": null,
            "assists": 14,
            "backpack_0": 0,
            "backpack_1": 0,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 6,
            "denies": 3,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 1839,
            "gold_per_min": 1392,
            "gold_reasons": null,
            "gold_spent": 33250,
            "gold_t": null,
            "hero_damage": 14506,
            "hero_healing": 0,
            "hero_hits": null,
            "hero_id": 41,
            "item_0": 172,
            "item_1": 158,
            "item_2": 116,
            "item_3": 154,
            "item_4": 63,
            "item_5": 141,
            "item_neutral": 638,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 4,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 183,
            "leaver_status": 0,
            "level": 28,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 33914,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 3,
            "party_size": 2,
            "performance_others": null,
            "permanent_buffs": [
                {
                    "permanent_buff": 1,
                    "stack_count": 0,
                    "grant_time": 1529
                },
                {
                    "permanent_buff": 2,
                    "stack_count": 0,
                    "grant_time": 1638
                },
                {
                    "permanent_buff": 6,
                    "stack_count": 1,
                    "grant_time": 838
                }
            ],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 14330,
            "towers_killed": null,
            "xp_per_min": 1866,
            "xp_reasons": null,
            "xp_t": null,
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": false,
            "win": 1,
            "lose": 0,
            "total_gold": 34104,
            "total_xp": 45717,
            "kills_per_min": 0.16326530612244897,
            "kda": 2,
            "abandons": 0,
            "rank_tier": null,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 1392,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1866,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.16326530612244897,
                    "pct": 0.36666666666666664
                },
                "last_hits_per_min": {
                    "raw": 7.469387755102041,
                    "pct": 0.4666666666666667
                },
                "hero_damage_per_min": {
                    "raw": 592.0816326530612,
                    "pct": 0.5
                },
                "hero_healing_per_min": {
                    "raw": 0,
                    "pct": 1
                },
                "tower_damage": {
                    "raw": 14330,
                    "pct": 0.9666666666666667
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0.03333333333333333
                },
                "lhten": {}
            }
        },
        {
            "match_id": 7065049753,
            "player_slot": 130,
            "ability_targets": null,
            "ability_upgrades_arr": [
                5286,
                5287,
                5286,
                5285,
                5286,
                5288,
                5286,
                5285,
                5285,
                484,
                5285,
                5288,
                5287,
                5287,
                959,
                5287,
                5288,
                6018,
                877,
                869,
                876,
                878,
                7040
            ],
            "ability_uses": null,
            "account_id": 113301755,
            "actions": null,
            "additional_units": null,
            "assists": 14,
            "backpack_0": 0,
            "backpack_1": 0,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 5,
            "denies": 3,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 5190,
            "gold_per_min": 2137,
            "gold_reasons": null,
            "gold_spent": 49225,
            "gold_t": null,
            "hero_damage": 32584,
            "hero_healing": 0,
            "hero_hits": null,
            "hero_id": 62,
            "item_0": 96,
            "item_1": 235,
            "item_2": 610,
            "item_3": 114,
            "item_4": 220,
            "item_5": 600,
            "item_neutral": 949,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 13,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 50,
            "leaver_status": 0,
            "level": 30,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 50465,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 4,
            "party_size": 1,
            "performance_others": null,
            "permanent_buffs": [
                {
                    "permanent_buff": 1,
                    "stack_count": 0,
                    "grant_time": 1617
                },
                {
                    "permanent_buff": 2,
                    "stack_count": 0,
                    "grant_time": 1373
                },
                {
                    "permanent_buff": 10,
                    "stack_count": 9819,
                    "grant_time": 130
                },
                {
                    "permanent_buff": 12,
                    "stack_count": 0,
                    "grant_time": 1618
                }
            ],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 1768,
            "towers_killed": null,
            "xp_per_min": 1815,
            "xp_reasons": null,
            "xp_t": null,
            "personaname": "MinM",
            "name": null,
            "last_login": null,
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": false,
            "win": 1,
            "lose": 0,
            "total_gold": 52356,
            "total_xp": 44467,
            "kills_per_min": 0.5306122448979592,
            "kda": 4,
            "abandons": 0,
            "rank_tier": 33,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 2137,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1815,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.5306122448979592,
                    "pct": 1
                },
                "last_hits_per_min": {
                    "raw": 2.0408163265306123,
                    "pct": 0.5555555555555556
                },
                "hero_damage_per_min": {
                    "raw": 1329.9591836734694,
                    "pct": 1
                },
                "hero_healing_per_min": {
                    "raw": 0,
                    "pct": 0.9444444444444444
                },
                "tower_damage": {
                    "raw": 1768,
                    "pct": 0.8888888888888888
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0.1111111111111111
                },
                "lhten": {}
            }
        },
        {
            "match_id": 7065049753,
            "player_slot": 131,
            "ability_targets": null,
            "ability_upgrades_arr": [
                5088,
                5086,
                5087,
                5086,
                5088,
                5089,
                5087,
                5087,
                5088,
                5088,
                5087,
                5089,
                5086,
                5086,
                6822,
                1041,
                5089,
                6821,
                6566,
                6088,
                809,
                6801,
                741
            ],
            "ability_uses": null,
            "account_id": 90562736,
            "actions": null,
            "additional_units": null,
            "assists": 12,
            "backpack_0": 0,
            "backpack_1": 0,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 3,
            "denies": 2,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 5601,
            "gold_per_min": 1447,
            "gold_reasons": null,
            "gold_spent": 30765,
            "gold_t": null,
            "hero_damage": 19043,
            "hero_healing": 0,
            "hero_hits": null,
            "hero_id": 42,
            "item_0": 1,
            "item_1": 168,
            "item_2": 247,
            "item_3": 208,
            "item_4": 112,
            "item_5": 63,
            "item_neutral": 573,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 5,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 135,
            "leaver_status": 0,
            "level": 30,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 35426,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 5,
            "party_size": 2,
            "performance_others": null,
            "permanent_buffs": [
                {
                    "permanent_buff": 2,
                    "stack_count": 0,
                    "grant_time": 1625
                },
                {
                    "permanent_buff": 12,
                    "stack_count": 0,
                    "grant_time": 915
                }
            ],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 10179,
            "towers_killed": null,
            "xp_per_min": 1604,
            "xp_reasons": null,
            "xp_t": null,
            "personaname": "Paskal'",
            "name": null,
            "last_login": null,
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": false,
            "win": 1,
            "lose": 0,
            "total_gold": 35451,
            "total_xp": 39298,
            "kills_per_min": 0.20408163265306123,
            "kda": 4,
            "abandons": 0,
            "rank_tier": 51,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 1447,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1604,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.20408163265306123,
                    "pct": 0.5652173913043478
                },
                "last_hits_per_min": {
                    "raw": 5.510204081632653,
                    "pct": 0.2608695652173913
                },
                "hero_damage_per_min": {
                    "raw": 777.265306122449,
                    "pct": 0.6956521739130435
                },
                "hero_healing_per_min": {
                    "raw": 0,
                    "pct": 1
                },
                "tower_damage": {
                    "raw": 10179,
                    "pct": 0.6086956521739131
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0
                },
                "lhten": {}
            }
        },
        {
            "match_id": 7065049753,
            "player_slot": 132,
            "ability_targets": null,
            "ability_upgrades_arr": [
                5347,
                5345,
                5347,
                5345,
                5347,
                5348,
                5346,
                5347,
                5345,
                5345,
                5346,
                5348,
                5346,
                5346,
                7652,
                6214,
                5348,
                6291,
                7106
            ],
            "ability_uses": null,
            "account_id": 135070877,
            "actions": null,
            "additional_units": null,
            "assists": 15,
            "backpack_0": 265,
            "backpack_1": 40,
            "backpack_2": 0,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": null,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": 5,
            "denies": 1,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": 1367,
            "gold_per_min": 890,
            "gold_reasons": null,
            "gold_spent": 21045,
            "gold_t": null,
            "hero_damage": 16733,
            "hero_healing": 867,
            "hero_hits": null,
            "hero_id": 68,
            "item_0": 55,
            "item_1": 176,
            "item_2": 36,
            "item_3": 214,
            "item_4": 534,
            "item_5": 92,
            "item_neutral": 825,
            "item_uses": null,
            "kill_streaks": null,
            "killed": null,
            "killed_by": null,
            "kills": 4,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": 33,
            "leaver_status": 0,
            "level": 27,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": 21277,
            "obs": null,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": 5,
            "party_size": 2,
            "performance_others": null,
            "permanent_buffs": [
                {
                    "permanent_buff": 2,
                    "stack_count": 0,
                    "grant_time": 1213
                }
            ],
            "pings": null,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": null,
            "rune_pickups": null,
            "runes": null,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": null,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": 937,
            "towers_killed": null,
            "xp_per_min": 1463,
            "xp_reasons": null,
            "xp_t": null,
            "personaname": "Ｅｖｏｃｈｋａ　翁ー",
            "name": null,
            "last_login": "2020-02-10T14:15:17.300Z",
            "radiant_win": false,
            "start_time": 1679081451,
            "duration": 1470,
            "cluster": 185,
            "lobby_type": 0,
            "game_mode": 23,
            "is_contributor": false,
            "patch": 51,
            "region": 8,
            "isRadiant": false,
            "win": 1,
            "lose": 0,
            "total_gold": 21805,
            "total_xp": 35843,
            "kills_per_min": 0.16326530612244897,
            "kda": 3,
            "abandons": 0,
            "rank_tier": 32,
            "is_subscriber": false,
            "cosmetics": [],
            "benchmarks": {
                "gold_per_min": {
                    "raw": 890,
                    "pct": 1
                },
                "xp_per_min": {
                    "raw": 1463,
                    "pct": 1
                },
                "kills_per_min": {
                    "raw": 0.16326530612244897,
                    "pct": 0.5714285714285714
                },
                "last_hits_per_min": {
                    "raw": 1.346938775510204,
                    "pct": 0.5714285714285714
                },
                "hero_damage_per_min": {
                    "raw": 682.9795918367347,
                    "pct": 0.6428571428571429
                },
                "hero_healing_per_min": {
                    "raw": 35.38775510204081,
                    "pct": 1
                },
                "tower_damage": {
                    "raw": 937,
                    "pct": 0.5714285714285714
                },
                "stuns_per_min": {
                    "raw": 0,
                    "pct": 0
                },
                "lhten": {}
            }
        }
    ],
    "patch": 51,
    "region": 8,
    "replay_url": "http://replay185.valve.net/570/7065049753_1209713151.dem.bz2"
}